### ISSUE TITLE
Question about runtime setup please

### ISSUE THREAD

**Issue by matanster** [clulab/processors#19]
Hi Mihai,

I seem to really suck at guessing the sbt configuration for safely running the sample code at https://github.com/sistanlp/processors#annotating-entire-documents within my own application. I made my way through adding the necessary imports, after having added the maven dependency in my build.sbt, and hoped for good. I get the below exception for the line `val doc = proc.annotate("John Smith went to China. He visited Beijing, on January 10th, 2013.")`

```
00:11:17.670 [run-main-0] DEBUG e.a.s.discourse.rstparser.RSTParser - Loading RST parsing model from: edu/arizona/sista/discourse/rstparser/model.const.rst.gz
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:76)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:90)
	at edu.arizona.sista.discourse.rstparser.RSTParser$.loadFrom(RSTParser.scala:202)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor$.fetchParser(CoreNLPProcessor.scala:465)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.rstConstituentParser$lzycompute(CoreNLPProcessor.scala:36)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.rstConstituentParser(CoreNLPProcessor.scala:36)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.discourse(CoreNLPProcessor.scala:453)
	at edu.arizona.sista.processors.Processor$class.annotate(Processor.scala:75)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.annotate(CoreNLPProcessor.scala:25)
	at edu.arizona.sista.processors.Processor$class.annotate(Processor.scala:54)
	at edu.arizona.sista.processors.corenlp.CoreNLPProcessor.annotate(CoreNLPProcessor.scala:25)
	at my scala line of code copied above .....
	at Boot$delayedInit$body.apply(Boot.scala:14)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.App$$anonfun$main$1.apply(App.scala:71)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
	at scala.App$class.main(App.scala:71)
	at Boot$.main(Boot.scala:4)
	at Boot.main(Boot.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

Can you please advise what should I include in my build configuration, env variables or classpath, in order to include everything that's needed for run time?

Should I really avoid Java 7 with version `3.3`?
I added the following in my `build.sbt` to that effect:

```
scalaVersion  := "2.10.4"
scalacOptions += "-target:jvm-1.6"
javacOptions ++= Seq("-source", "1.6", "-target", "1.6")
```

I have specifically installed Oracle Java 6 now for this (I had only Java 7 before on the current machine), but I think that all should not be required as I assume my Java 7 code should be able to use Java 6 class files. So some advice would come in very much appreciated here....

**Comment by MihaiSurdeanu** [comment]
Hi,

Most of the code works with Java 7 now, with the exception of some concurrency unit tests. If multi-threading is important for your application, I suggest staying with Java 6 byte code. This can be enforced even when the underlying JVM is Java 7, with these sbt options:
  scalacOptions += "-target:jvm-1.6"
  javacOptions ++= Seq("-source", "1.6", "-target", "1.6")
All our unit tests pass with Java 7, if the above options are present.

Wrt the above Exception, that happens when the runtime doesn't find the processors-*-models.jar. To make sure this is include in the class path, add these dependencies to the sbt of your project:
  "edu.arizona.sista" %% "processors" % "4.0-SNAPSHOT",
  "edu.arizona.sista" %% "processors" % "4.0-SNAPSHOT" classifier "models",

(If you make changes to the processors source code, make sure to run "sbt publish-local" in the processors project to install the new jars in the correct locations for sbt to see them)

**Comment by MihaiSurdeanu** [comment]
This is fixed?
We can open it again, if not.
