### ISSUE TITLE
BioNLPProcessor.annotate fails when withRuleNER is set to false

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#255]
@MihaiSurdeanu, it seems that `BioNLPProcessor.annotate` now fails when `withRuleNER` is set to `false`, even if `withCRFNER` is set to `true`:

```
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:347)
  at scala.None$.get(Option.scala:345)
  at org.clulab.processors.clu.bio.BioNERPostProcessor.process(BioNERPostProcessor.scala:23)
  at org.clulab.processors.bionlp.BioNLPProcessor$$anonfun$recognizeNamedEntities$1.apply(BioNLPProcessor.scala:59)
  at org.clulab.processors.bionlp.BioNLPProcessor$$anonfun$recognizeNamedEntities$1.apply(BioNLPProcessor.scala:58)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.clulab.processors.bionlp.BioNLPProcessor.recognizeNamedEntities(BioNLPProcessor.scala:58)
  at org.clulab.processors.Processor$class.annotate(Processor.scala:89)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:29)
  at org.clulab.processors.Processor$class.annotate(Processor.scala:59)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:29)
```

This is due to `BioNERPostProcessor` attempting to access the `.entities` attribute of each sentence it processes.

- https://github.com/clulab/processors/blob/12b6dcebfd66166fa063568d70e36bf163fe8717/corenlp/src/main/scala/org/clulab/processors/bionlp/BioNLPProcessor.scala#L59
- https://github.com/clulab/processors/blob/12b6dcebfd66166fa063568d70e36bf163fe8717/main/src/main/scala/org/clulab/processors/clu/bio/BioNERPostProcessor.scala#L23

One option is to change `recognizeNamedEntities`:

```scala
  override def recognizeNamedEntities(doc:Document) {
    hybridNER.recognizeNamedEntities(doc, namedEntitySanityCheck(doc))

    for {
      sentence <- doc.sentences
      // only post-process if we have entities
      if sentence.entities.nonEmpty
    } { nerPostProcessor.process(sentence) }
  }
```

I think it would be better to handle it in [`BioNERPostProcessor.process` instead, though](https://github.com/clulab/processors/blob/12b6dcebfd66166fa063568d70e36bf163fe8717/main/src/main/scala/org/clulab/processors/clu/bio/BioNERPostProcessor.scala#L22).

**Comment by MihaiSurdeanu** [comment]
Hi @myedibleenso: yes, you are correct. Can you please commit the fix in your comment?
Thanks!

**Comment by kwalcock** [comment]
This has been moved to https://github.com/clulab/reach/issues/781.
