### ISSUE TITLE
CluProcessor.annotate fails with space in path to JAR file

### ISSUE THREAD

**Issue by JohnDaws** [clulab/processors#264]
`CluProcessor.annotate` fails with the error:

```
java.io.FileNotFoundException: C:\Users\John\Documents\clu_test\with%20space\target\test-app-1.0-SNAPSHOT.jar (The system cannot find the path specified)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.zip.ZipFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at java.util.jar.JarFile.<init>(Unknown Source)
        at org.clulab.utils.Files$.extractEntry(Files.scala:89)
        at org.clulab.processors.clu.syntax.MaltWrapper.mkMaltModel(MaltWrapper.scala:59)
        at org.clulab.processors.clu.syntax.MaltWrapper.maltModel$lzycompute(MaltWrapper.scala:28)
        at org.clulab.processors.clu.syntax.MaltWrapper.maltModel(MaltWrapper.scala:28)
        at org.clulab.processors.clu.syntax.MaltWrapper.parseSentenceConllx(MaltWrapper.scala:81)
        at org.clulab.processors.clu.syntax.EnsembleMaltParser$$anonfun$ensembleParse$1.apply(EnsembleMaltParser.scala:36)
        at org.clulab.processors.clu.syntax.EnsembleMaltParser$$anonfun$ensembleParse$1.apply(EnsembleMaltParser.scala:35)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.clulab.processors.clu.syntax.EnsembleMaltParser.ensembleParse(EnsembleMaltParser.scala:35)
        at org.clulab.processors.clu.syntax.EnsembleMaltParser.parseSentence(EnsembleMaltParser.scala:28)
        at org.clulab.processors.clu.CluProcessor$$anonfun$parse$1.apply(CluProcessor.scala:315)
        at org.clulab.processors.clu.CluProcessor$$anonfun$parse$1.apply(CluProcessor.scala:313)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.clulab.processors.clu.CluProcessor.parse(CluProcessor.scala:313)
        at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:120)
        at org.clulab.processors.Processor$class.annotate(Processor.scala:61)
        at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:31)
        at com.test.app.ProcessorsExample.main(ProcessorsExample.java:31)
```
when run from inside a JAR file where the path to the JAR file contains a space.

This can be reproduced with this code
```
      CluProcessor proc;
      proc = new CluProcessor(ConfigFactory.load("cluprocessoropen"));
      Document doc=proc.annotate("John Smith went to China. He visited Beijing, on January 10th, 2013.", false);    	
```
and the following imports:
```
import org.clulab.processors.clu.CluProcessor;
import org.clulab.processors.Document;
import com.typesafe.config.ConfigFactory;
```
The issue is caused in [mkMaltModel](https://github.com/clulab/processors/blob/a175db65119bbd06f66fc0844461b490a395fae0/main/src/main/scala/org/clulab/processors/clu/syntax/MaltWrapper.scala) where the space in the JAR path is URL encoded as %20 which causes the `FileNotFoundException` within `ZipFile.open`.

**Comment by MihaiSurdeanu** [comment]
Hmm... @kwalcock: can you please take a look? I am sure I get this...

**Comment by marcovzla** [comment]
seems like the space was urlencoded into `%20`,
maybe that's the issue?

**Comment by MihaiSurdeanu** [comment]
Yes, but I don't see where this is happening...

**Comment by kwalcock** [comment]
It sounds like ZipFile.open is expecting a (mostly) decoded filename and is instead getting something that has been urlencoded.  I haven't had time to look yet.

**Comment by kwalcock** [comment]
Please see PR #265.

**Comment by JohnDaws** [comment]
Thank you for looking into this so promptly.

I assume that PR#265 is not complete yet, as I only see one commit that to my no experience in scala eye only contains a stub of a test function.

If it helps, I have looked a bit deeper into your code, but do not have the scala skills to suggest a fix, but hopefully the following extra information is useful...

The issue appears to stem from `mkMaltModel` in [maltWrapper.scala](https://github.com/clulab/processors/blob/a175db65119bbd06f66fc0844461b490a395fae0/main/src/main/scala/org/clulab/processors/clu/syntax/MaltWrapper.scala)

* At `line 42` the model resource within the JAR is returned as a URL.
* At `line 44` this is converted to a string. This string is url encoded and in my case has `%20` instead of a space in the path to the JAR file.
* At `line 52` `jar:file:` is removed from the start of the JAR file url and the end is trimmed off from the last `/`. This should leave the file path to the JAR file, expect that it remains URL encoded which causes a problem at `line 59` somewhere inside `Files.extractEntry` as the `jarFileName` provided cannot be opened due to the URL encoding.

It looks to me like `line 52` needs to be made a little more robust, by decoding the URL as well as trimming off the unnecessary characters at the start and end.

**Comment by JohnDaws** [comment]
Further to the above, changing `line 52` of  (maltWrapper.scala)[https://github.com/clulab/processors/blob/a175db65119bbd06f66fc0844461b490a395fae0/main/src/main/scala/org/clulab/processors/clu/syntax/MaltWrapper.scala] to 
`      val jarFileName = URLDecoder.decode(path.substring(9, jarEnd), "UTF-8")`
with the additional import
`import java.net.URLDecoder`
seems to make the issue go away.

I've not been able to build the project and verify that this change doesn't have any side effects, but hopefully it'll help you close this down.

**Comment by kwalcock** [comment]
Well, that's embarassing.  I appear to have checked in the wrong file somehow.

**Comment by kwalcock** [comment]
And yes, that's exactly the correct change to make.  Good call.

**Comment by JohnDaws** [comment]
Great. Thanks for sorting this out!

**Comment by kwalcock** [comment]
The fix is merged into master.  I'm not sure when it will propagate to a formal, numbered release.
