### ISSUE TITLE
making a document from sentences

### ISSUE THREAD

**Issue by bsharpataz** [clulab/processors#285]
Maybe not a bug, but I can't seem to make this pipeline work.  I am interested in making a document from a subset of the sentences from a previously made document, prior to annotating (the whole reason I want to do this is to avoid annotating crazy long sentences).  Then, after making the subset, I want to annotate.  But... seems the constructor doesn't make a CoreNLPDocument, and if I try to co-opt the conversion method in ShallowNLPProcessor to convert it, it's unhappy.  I don't know how to do this, maybe I have the wrong pipeline... thanks for the help!! 

Here's a MWE:
import org.clulab.processors.fastnlp.FastNLPProcessor
import org.clulab.processors.Document

val proc = new FastNLPProcessor
val d = proc.mkDocument("This is a sentence")
// make a new document using the constructor from Document.scala
val d2 = Document(d.sentences)
// annotate it
val a = proc.annotate(d2)

```
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:349)
  at scala.None$.get(Option.scala:347)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.$anonfun$chunking$1(ShallowNLPProcessor.scala:237)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.$anonfun$chunking$1$adapted(ShallowNLPProcessor.scala:235)
  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.chunking(ShallowNLPProcessor.scala:235)
  at org.clulab.processors.Processor.annotate(Processor.scala:91)
  at org.clulab.processors.Processor.annotate$(Processor.scala:86)
  at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:29)
  ... 36 elided```

**Comment by MihaiSurdeanu** [comment]
Yeah, that is ambiguous. The functionality you want is in Processor.mkDocumentFromSentences or mkDocumentFromTokens:

https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/Processor.scala#L16

Does that work?

**Comment by kwalcock** [comment]
This is a reminder to myself to see if this is where one might selectively filter out sentences of a long document and then try to process the document in parts and splice it back together afterwards.  If a document has 300 sentences, run [0-100) as if all the other sentences were too long, then [100, 200), then [200, 300), and at the end combine the documents.  At some point I called these chapters and there might be a record somewhere.  This is to compensate for nonlinearity in processing time if other means don't work.
