### ISSUE TITLE
Issue when using buildMatrix method in Word2Vec.scala

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/processors#291]
I am trying to run EBP.scala (can be found here: https://github.com/clulab/research/tree/daa61572c7dc551ecf62078363bb2d7777689d90/clint/src/main/scala/org/clulab/clint). 

I am getting an error that seems to be coming from here: 
https://github.com/clulab/processors/blob/6cf2291418c063ef9a429708ab064b2842a0bb20/main/src/main/scala/org/clulab/embeddings/word2vec/Word2Vec.scala#L431

Here's the line from EBP.scala: https://github.com/clulab/research/blob/6083d13226ab98e8b4a3c22c9c92f67a6214ddc3/clint/src/main/scala/org/clulab/clint/EPB.scala#L70

Is the input in line 70 in EBP supposed to be a file with embedding vectors? The config file called for this file (which I do not have): vectors.goldbergdeps.txt. Since I don't have the file and am not sure what is supposed to be in the file, I was trying glove and dependency-based embeddings. 

Is _dim_  (line 431 in the word2vec file) the dimensions of the embedding? If yes, what is the purpose of _toInt_ applied to the element indexed 1? 

This is the whole error I am getting:

```
[info] Running org.clulab.clint.EPB 
21:09:35.696 [run-main-0] INFO org.clulab.clint.EPB$ - loading data
21:09:36.185 [run-main-0] DEBUG org.clulab.embeddings.word2vec.Word2Vec - Started to load word2vec matrix from file /home/masha/Embeddings/deps.words...
[error] (run-main-0) java.lang.NumberFormatException: For input string: "-0.0279698616277"
java.lang.NumberFormatException: For input string: "-0.0279698616277"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike.toInt(StringLike.scala:301)
        at scala.collection.immutable.StringLike.toInt$(StringLike.scala:301)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
        at org.clulab.embeddings.word2vec.Word2Vec$.$anonfun$buildMatrix$2(Word2vec.scala:479)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at org.clulab.embeddings.word2vec.Word2Vec$.buildMatrix(Word2vec.scala:476)
        at org.clulab.embeddings.word2vec.Word2Vec$.org$clulab$embeddings$word2vec$Word2Vec$$loadMatrix(Word2vec.scala:448)
        at org.clulab.embeddings.word2vec.Word2Vec$$anonfun$$lessinit$greater$1.apply(Word2vec.scala:28)
        at org.clulab.embeddings.word2vec.Word2Vec$$anonfun$$lessinit$greater$1.apply(Word2vec.scala:28)
        at org.clulab.embeddings.word2vec.Word2Vec.<init>(Word2vec.scala:42)
        at org.clulab.embeddings.word2vec.Word2Vec.<init>(Word2vec.scala:28)
        at org.clulab.clint.EPB$.delayedEndpoint$org$clulab$clint$EPB$1(EPB.scala:72)
        at org.clulab.clint.EPB$delayedInit$body.apply(EPB.scala:26)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at org.clulab.clint.EPB$.main(EPB.scala:26)
        at org.clulab.clint.EPB.main(EPB.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
[trace] Stack trace suppressed: run last compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 4 s, completed Jan 8, 2019 9:09:36 PM
```

**Comment by maxaalexeeva** [comment]
I also see now that the version of processors used in the project I'm working won is 7.1.0. Tried the latest version, but haven't managed to get it to compile yet.

**Comment by marcovzla** [comment]
I believe you should be using a file with embeddings in the word2vec format, which begins with two integers: size of vocabulary and number of dimensions.

**Comment by maxaalexeeva** [comment]
@marcovzla thank you! That makes sense. Neither of the vector files I downloaded has those :/ I will try that.
