### ISSUE TITLE
LexiconNER not serializable from outside of processors

### ISSUE THREAD

**Issue by danebell** [clulab/processors#296]
It is apparently not currently possible to deserialize `LexiconNER` outside of processors. I have two suggests for the fix:

1. Remove the private restriction on `LexiconNER`'s constructor, so that others can do custom serialization/deserialization.
2. Create custom serialization/deserialization functions within `LexiconNER` for projects outside processors to use.

Example:

```
import org.clulab.sequences.LexiconNER
import java.util.zip.{GZIPInputStream, GZIPOutputStream}
import java.io.{File, FileInputStream, FileOutputStream, ObjectInputStream, ObjectOutputStream}

// create LexiconNER using the object's apply function
// to recreate this, you must use a list with at least one real KB (i.e., not Nil)
val lexiconNer1 = LexiconNER(List("path/to/kb.tar.gz"))

// serialize the model (works fine)
val modelPath = "model.ser.gz"
val outStream = new ObjectOutputStream(new GZIPOutputStream(new FileOutputStream(modelPath)))
outStream.writeObject(lexiconNer1)
outStream.close()

// attempt to deserialize
val inStream = new ObjectInputStream(new GZIPInputStream(new FileInputStream(modelPath)))
val lexiconNer2 = inStream.readObject().asInstanceOf[LexiconNER]
```

Expected behavior: `lexiconNer1` is indistinguishable from `lexiconNer2`.

Current behavior: This last line produces the following error.

```
java.lang.ClassNotFoundException: org.clulab.struct.TrieNode
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at java.lang.Class.forName0(Native Method)
  at java.lang.Class.forName(Class.java:348)
  at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:686)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1868)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2042)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
  at scala.collection.mutable.HashMap.$anonfun$readObject$1(HashMap.scala:189)
  at scala.collection.mutable.HashTable.init(HashTable.scala:108)
  at scala.collection.mutable.HashTable.init$(HashTable.scala:87)
  at scala.collection.mutable.HashMap.init(HashMap.scala:40)
  at scala.collection.mutable.HashMap.readObject(HashMap.scala:189)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
  at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1975)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1567)
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2287)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
```

**Comment by kwalcock** [comment]
There may soon be reason to make additional changes to LexiconNER that may affect serialization.  The issue is being written up.  Is there any chance that use of ClassLoaderObjectInputStream in place of ObjectInputStream would help?  There are some examples of it in the code and it seems like that sometimes helped with the ClassNotFoundException.

**Comment by MihaiSurdeanu** [comment]
+1 on @kwalcock's suggestion. I don't know if it will fix this, but it's cheap to try.

**Comment by kwalcock** [comment]
I believe this problem to have been solved in the meantime.  In TestLexiconNER there is a serialization test which has been passing for a long time.  I added this specific code and it passes as well without further changes.  There presently is no TrieNode class whatsoever.  In one or another revision of the LexiconNER, this problem was probably encountered and fixed.
