### ISSUE TITLE
Lemmas should not be empty

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#371]
I am parsing the docs with processors 7.5.4
I am just getting started, but I already ran into an issue and I thought you should know.

I have attached the file that causes the error. The assertion at https://github.com/clulab/processors/blob/v7.5.4/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L177 checks that the lemmas shouldn't be empty. I haven't checked beyond that.

This is the error:

2020-03-19 12:52:12 [scala-execution-context-global-182] ERROR ai.lum.odinson.extra.AnnotateText$ - Failed to process CORD19_DOC_2762.txt
java.lang.AssertionError: assertion failed
at scala.Predef$.assert(Predef.scala:208)
at org.clulab.processors.clu.CluProcessor.$anonfun$lemmatize$2(CluProcessor.scala:177)
at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
at org.clulab.processors.clu.CluProcessor.$anonfun$lemmatize$1(CluProcessor.scala:175)
at org.clulab.processors.clu.CluProcessor.$anonfun$lemmatize$1$adapted(CluProcessor.scala:172)
at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
at org.clulab.processors.clu.CluProcessor.lemmatize(CluProcessor.scala:172)
at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:125)
at org.clulab.processors.Processor.annotate(Processor.scala:62)
at org.clulab.processors.Processor.annotate$(Processor.scala:59)
at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:27)
at ai.lum.odinson.extra.AnnotateText$.annotateTextFile(AnnotateText.scala:36)
at ai.lum.odinson.extra.AnnotateText$.$anonfun$new$2(AnnotateText.scala:50)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.util.Try$.apply(Try.scala:213)
at ai.lum.odinson.extra.AnnotateText$.$anonfun$new$1(AnnotateText.scala:49)
at ai.lum.odinson.extra.AnnotateText$.$anonfun$new$1$adapted(AnnotateText.scala:43)
at scala.collection.Iterator.foreach(Iterator.scala:941)
at scala.collection.Iterator.foreach$(Iterator.scala:941)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:974)
at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:971)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by MihaiSurdeanu** [comment]
@marcovzla: this was fixed in PR #372 .
The other bug you reported comes from maltparser, which is longer included in processors, so I won't fix that.
