### ISSUE TITLE
java.lang.NumberFormatException: For input string: "<STOP>"

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#424]
Running on branch parallel and in parallel with CluProcessor, this exception occurs during annotation.  I will attach a file if/when it can be reproduced.

```
Processing 9_FAOSS Livestock Crisis Update 2015.txt...
Processing 32_sudantribune.txt...
Processing 33_Achievement of household food security in South Sudan - Sudan Tribune_ Plural news and views on Sudan.txt...
Processing 31_South_Sudan_2018_Humanitarian_Needs_Overview.txt...
Processing 11_FAO_a-i5591e.txt...
Processing 12_SSD21-February-2017.txt...
Processing 26_South_Sudan_2018_Humanitarian_Needs_Overview.txt...
Processing 27_South Sudan_ Floods - Sep 2017 _ ReliefWeb.txt...
Processing 4_FAO.txt...
Processing 50_wfp280481.txt...
[error] (run-main-0) java.lang.NumberFormatException: For input string: "<STOP>"
[error] java.lang.NumberFormatException: For input string: "<STOP>"
[error]         at java.lang.NumberFormatException.forInputString(Unknown Source)
[error]         at java.lang.Integer.parseInt(Unknown Source)
[error]         at java.lang.Integer.parseInt(Unknown Source)
[error]         at scala.collection.immutable.StringLike.toInt(StringLike.scala:301)
[error]         at scala.collection.immutable.StringLike.toInt$(StringLike.scala:301)
[error]         at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
[error]         at org.clulab.processors.clu.CluProcessor.$anonfun$parseSentence$3(CluProcessor.scala:199)
[error]         at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:156)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at org.clulab.processors.clu.CluProcessor.$anonfun$parseSentence$1(CluProcessor.scala:198)
[error]         at org.clulab.processors.clu.CluProcessor.$anonfun$parseSentence$1$adapted(CluProcessor.scala:193)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:156)
[error]         at org.clulab.processors.clu.CluProcessor.parseSentence(CluProcessor.scala:193)
[error]         at org.clulab.processors.clu.CluProcessor.$anonfun$parse$1(CluProcessor.scala:419)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
[error]         at org.clulab.processors.clu.CluProcessor.parse(CluProcessor.scala:418)
[error]         at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:91)
[error]         at org.clulab.processors.Processor.annotate(Processor.scala:65)
[error]         at org.clulab.processors.Processor.annotate$(Processor.scala:62)
[error]         at org.clulab.processors.clu.CluProcessor.annotate(CluProcessor.scala:22)
[error]         at org.clulab.processors.examples.ParallelProcessorExample$.$anonfun$mainWithCallback$2(ParallelProcessorExample.scala:152)
[error]         at org.clulab.processors.examples.ParallelProcessorExample$.$anonfun$mainWithCallback$2$adapted(ParallelProcessorExample.scala:140)
[error]         at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
[error]         at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
[error]         at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
[error]         at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
[error]         at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
[error]         at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:166)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
[error]         at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
[error]         at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
[error]         at java.util.concurrent.RecursiveAction.exec(Unknown Source)
[error]         at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by kwalcock** [comment]
The word "STOP" is not in the file, so it must be inserted by something.  I doubt that the parallelization has anything to do with it.  It happens if the file is run alone.

[50_wfp280481.txt](https://github.com/clulab/processors/files/5247477/50_wfp280481.txt)

**Comment by kwalcock** [comment]
CluProcessor

**Comment by MihaiSurdeanu** [comment]
Thanks!
I'll take a look soon.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: this has been fixed in the "parallel" branch. Thanks for catching it!

**Comment by kwalcock** [comment]
It no longer crashes.  I'm working on timings then.

**Comment by MihaiSurdeanu** [comment]
Nice!
