### ISSUE TITLE
DyNet finds bad input dimensions in something that processor gives it

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#436]
This is coming from the FastNLPProcessorWithSemanticRoles after running ExtractSemanticRolesRandom for a long time.  This is the first time C++ threw an exception that was caught in Java.  I'm trying to narrow it down.

```
Exception in thread "main" java.lang.IllegalArgumentException: Bad input dimensions in Concatenate: [{128} {64,16}]
	at edu.cmu.dynet.internal.dynet_swigJNI.concatenate__SWIG_1(Native Method)
	at edu.cmu.dynet.internal.dynet_swig.concatenate(dynet_swig.java:655)
	at edu.cmu.dynet.Expression$.$anonfun$concatenate$1(Expression.scala:273)
	at edu.cmu.dynet.Expression$.vectory(Expression.scala:139)
	at edu.cmu.dynet.Expression$.concatenate(Expression.scala:273)
	at edu.cmu.dynet.Expression$.concatenate(Expression.scala:274)
	at org.clulab.dynet.RnnLayer.$anonfun$forward$1(RnnLayer.scala:43)
	at org.clulab.dynet.RnnLayer.$anonfun$forward$1$adapted(RnnLayer.scala:39)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:156)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.clulab.dynet.RnnLayer.forward(RnnLayer.scala:39)
	at org.clulab.dynet.Layers.$anonfun$forward$1(Layers.scala:65)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
	at org.clulab.dynet.Layers.forward(Layers.scala:64)
	at org.clulab.dynet.Layers$.$anonfun$predictJointly$1(Layers.scala:209)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.clulab.dynet.DyNetSync$.withComputationGraph(DyNetSync.scala:19)
	at org.clulab.dynet.Layers$.predictJointly(Layers.scala:208)
	at org.clulab.dynet.Metal.predictJointly(Metal.scala:317)
	at org.clulab.processors.clu.CluProcessor.tagSentence(CluProcessor.scala:133)
	at org.clulab.processors.fastnlp.FastNLPProcessorWithSemanticRoles.$anonfun$srl$1(FastNLPProcessorWithSemanticRoles.scala:40)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:191)
	at org.clulab.processors.fastnlp.FastNLPProcessorWithSemanticRoles.srl(FastNLPProcessorWithSemanticRoles.scala:36)
	at org.clulab.processors.Processor.annotate(Processor.scala:97)
	at org.clulab.processors.Processor.annotate$(Processor.scala:90)
	at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:34)
	at org.clulab.processors.Processor.annotate(Processor.scala:65)
	at org.clulab.processors.Processor.annotate$(Processor.scala:62)
	at org.clulab.processors.shallownlp.ShallowNLPProcessor.annotate(ShallowNLPProcessor.scala:34)
	at org.clulab.ExtractSemanticRolesRandom$.$anonfun$new$2(ExtractSemanticRolesRandom.scala:60)
	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:142)
	at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
	at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

**Comment by BeckySharp** [comment]
merry christmas mihai!

**Comment by MihaiSurdeanu** [comment]
Unfortunately, this seems to come from this line:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/dynet/RnnLayer.scala#L43

which simply concatenates a forward and backward LSTM in a biLSTM. So that situation reported can't happen... Which might suggest that these vectors get corrupted somewhere else...

**Comment by kwalcock** [comment]
The exact same code and the same machine with the same random seed ran much longer the next time, maybe 8 hours.  Shortly before it crashed, it did note
```
06:29:28.286 [scala-execution-context-global-33] INFO  e.s.n.l.t.types.Expressions - Unknown variable: WORKDAY
```
which is new.  That seems to hint at corruption as well.

A different machine produced a crash in
```
# C  [dynet7443973151275228681.dll+0x119512]  dynet::ComputationGraph::set_dim_for_new_node(unsigned int const&)+0x122
```

The third machine is still running.

**Comment by kwalcock** [comment]
e.s.n.l.t.types.Expressions is edu.stanford.nlp.ling.tokensregex.types.Expressions FWIW.

**Comment by kwalcock** [comment]
I think this has been taken care of with the fix for ExpressionVector.
