### ISSUE TITLE
Make unit tests compile without dynet

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#742]
@kwalcock : I removed dynet from processors in the branch `balaur-minus-dynet`. I adjusted most unit tests, but this one does not compile:

```
[info] compiling 79 Scala sources to /home/msurdeanu/github/processors/main/target/scala-2.12/test-classes ...
[error] /home/msurdeanu/github/processors/main/src/test/scala/org/clulab/numeric/TestNumericEntityRecognition.scala:45:78: value tokenizer is not a member of org.clulab.processors.clu.BalaurProcessor
[error]     lazy val habitusTokenizer: HabitusTokenizer = new HabitusTokenizer(super.tokenizer)
[error]                                                                              ^
[error] one error found
[error] (main / Test / compileIncremental) Compilation failed
```

Can you please adjust it when you have a moment?

**Comment by MihaiSurdeanu** [comment]
Thanks to your PR, this test now passes. However, others failures showed up in the corenlp subproject. They are all caused by this error:

```
11:31:34.023 [pool-1-thread-1-ScalaTest-running-TestCoreNLPSentimentAnalyzer] INFO edu.stanford.nlp.parser.lexparser.LexicalizedParser - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0.1 sec].
[info] - should correctly assign sentiment scores for negative cases *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at java.util.zip.InflaterInputStream.<init>(InflaterInputStream.java:83)
[info]   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
[info]   at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.mkChunker(ShallowNLPProcessor.scala:84)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.chunker$lzycompute(ShallowNLPProcessor.scala:53)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.chunker(ShallowNLPProcessor.scala:53)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.$anonfun$chunking$1(ShallowNLPProcessor.scala:289)
[info]   at org.clulab.processors.shallownlp.ShallowNLPProcessor.$anonfun$chunking$1$adapted(ShallowNLPProcessor.scala:286)
[info]   at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[info]   at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[info]   ...
```

This error happens because this model:
https://github.com/clulab/processors/blob/balaur-minus-dynet/corenlp/src/main/scala/org/clulab/processors/shallownlp/ShallowNLPProcessor.scala#L82
is no longer available because I removed the dependency to processors-models, which includes it.
Can you please create a new jar file, let's call it `corenlp-additional-models`, which contains just this model?

Thank you!
Mihai

**Comment by kwalcock** [comment]
The file is 50MB and would fit on maven and github.  Although it is nice to have all the models in the same place (artifactory), it also requires the custom resolver in order to use.  Which would you rather have: maven/github or artifactory?  It could be github and artifactory.  Usually I don't make a github repo just to publish a resource on artifactory.

**Comment by kwalcock** [comment]
Perhaps even better, the file could be added to the processors-corenlp subproject as a resource and there wouldn't be an external dependency.

**Comment by MihaiSurdeanu** [comment]
Local resource would be best!
